### ISSUE TITLE
I get a warning when cloning the repo

### ISSUE THREAD

**Issue by mpagels** [ThomasF85/web-pool-tool#2]
I just cloned the repo and got this warning:
<img width="670" alt="Bildschirmfoto 2023-02-20 um 21 11 01" src="https://user-images.githubusercontent.com/54703643/220191024-7021ff41-c45a-4025-ac00-524614888295.png">

I'm on a MacBook M1.

Found this as well. This could be the issue: Two folders with the same name.
<img width="500" alt="Bildschirmfoto 2023-02-20 um 21 12 46" src="https://user-images.githubusercontent.com/54703643/220191267-71e62d92-3292-42ec-80d0-18409dcadeb5.png">

My Mac just changed this right after the cloning and got rid of the `forms` folder.

<img width="175" alt="Bildschirmfoto 2023-02-20 um 21 14 43" src="https://user-images.githubusercontent.com/54703643/220191377-f4867b76-b195-4246-a17e-e06bb2ceda9c.png">

<img width="515" alt="Bildschirmfoto 2023-02-20 um 21 15 35" src="https://user-images.githubusercontent.com/54703643/220191448-35d16fc9-3a50-47d8-b5df-632f631d0de5.png">

**Comment by ThomasF85** [comment]
You were right @mpagels the folders were remnants that could be deleted.
Thanks for bringing it up. The Issue should be fixed now.

**Comment by mpagels** [comment]
Just cloned it again and the error is gone. Thx.
